#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    File: collectord
    Description: Log Collector daemon.
"""

__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = "Ronald Kaiser"
__email__ = "ronald at intelie dot com dot br"


import optparse


if __name__ == '__main__':
    parser = optparse.OptionParser(version=__version__)
    (options, args) = parser.parse_args()
    if not args:
        parser.print_help()


