#!/bin/bash
#
# File: pycollectord
# chkconfig: 2345 64 36
# description: pycollector service wrapper 
# 


PYCOLLECTOR_BIN="/opt/intelie/pycollector/bin/pycollector"
USER="pycollector"
PYTHON_VERSION="python2.7"


case "$1" in 
    start)
        su -m $USER -c "$PYTHON_VERSION $PYCOLLECTOR_BIN --start"
        ;;
    stop)
        su -m $USER -c "$PYTHON_VERSION $PYCOLLECTOR_BIN --stop"
        ;;
    forcestop)
        su -m $USER -c "$PYTHON_VERSION $PYCOLLECTOR_BIN --forcestop"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        su -m $USER -c "$PYTHON_VERSION $PYCOLLECTOR_BIN --status"
        ;;
    *)
        echo "$0 {start|stop|forcestop|restart|status}"
        exit 1
        ;;
esac

exit 0
